name: ezmute Console Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.5

    - name: build
      run: dotnet build -c Release ezmute.sln
    - name: publish-standalone-win-x64
      run: dotnet publish -c Release ezmute.csproj -o /home/runner/work/ezmute-release/standalone-win-x64 -r win-x64 /p:PublishSingleFile=true --self-contained true /p:PublishTrimmed=true /p:CopyOutputSymbolsToPublishDirectory=false
    - name: publish-standalone-win-x32
      run: dotnet publish -c Release ezmute.csproj -o /home/runner/work/ezmute-release/standalone-win-x86 -r win-x86 /p:PublishSingleFile=true --self-contained true /p:PublishTrimmed=true /p:CopyOutputSymbolsToPublishDirectory=false
    - name: publish-win-x64
      run: dotnet publish -c Release ezmute.csproj -o /home/runner/work/ezmute-release/win-x64 -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:CopyOutputSymbolsToPublishDirectory=false
    - name: publish-win-x32
      run: dotnet publish -c Release ezmute.csproj -o /home/runner/work/ezmute-release/win-x86 -r win-x86 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:CopyOutputSymbolsToPublishDirectory=false
    - name: install-zip
      run: sudo apt update && sudo apt install zip unzip
    - name: make-zip-dir
      run: mkdir /home/runner/work/ezmute-release/zips
    - name: compress-standalone-win-x64
      run: pushd /home/runner/work/ezmute-release/standalone-win-x64 && zip -r /home/runner/work/ezmute-release/zips/ezmute-standalone-win-x64.zip * && popd
    - name: compress-standalone-win-x86
      run: pushd /home/runner/work/ezmute-release/standalone-win-x86 && zip -r /home/runner/work/ezmute-release/zips/ezmute-standalone-win-x86.zip * && popd
    - name: compress-standalone-win-x64
      run: pushd /home/runner/work/ezmute-release/win-x64 && zip -r /home/runner/work/ezmute-release/zips/ezmute-win-x64.zip * && popd
    - name: compress-standalone-win-x86
      run: pushd /home/runner/work/ezmute-release/win-x86 && zip -r /home/runner/work/ezmute-release/zips/ezmute-win-x86.zip * && popd
    - uses: actions/upload-artifact@v1
      with:
        name: octoplus--win-x64
        path: /home/runner/work/octoplus-release/zips/octoplus-win-x64.zip
    - uses: actions/upload-artifact@v1
      with:
        name: octoplus-win-x86
        path: /home/runner/work/octoplus-release/zips/octoplus-win-x86.zip