name: ezmute Release Build

on:
  push:
    branches:
      - v*

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '0'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: build
      run: dotnet build -c Release src\ezmute.sln
    - name: publish-standalone-win-x64
      run: dotnet publish -c Release src\ezmute.csproj -o d:\a\ezmute-release\standalone-win-x64 -r win-x64 /p:PublishSingleFile=true --self-contained true /p:PublishTrimmed=true /p:CopyOutputSymbolsToPublishDirectory=false
    - name: publish-standalone-win-x32
      run: dotnet publish -c Release src\ezmute.csproj -o d:\a\ezmute-release\standalone-win-x86 -r win-x86 /p:PublishSingleFile=true --self-contained true /p:PublishTrimmed=true /p:CopyOutputSymbolsToPublishDirectory=false
    - name: publish-win-x64
      run: dotnet publish -c Release src\ezmute.csproj -o d:\a\ezmute-release\win-x64 -r win-x64 /p:PublishSingleFile=true --self-contained false /p:CopyOutputSymbolsToPublishDirectory=false
    - name: publish-win-x32
      run: dotnet publish -c Release src\ezmute.csproj -o d:\a\ezmute-release\win-x86 -r win-x86 /p:PublishSingleFile=true --self-contained false /p:CopyOutputSymbolsToPublishDirectory=false
    - uses: actions/upload-artifact@v2
      with:
        name: ezmute-standalone-win-x64
        path: d:\a\ezmute-release\standalone-win-x64
    - uses: actions/upload-artifact@v2
      with:
        name: ezmute-standalone-win-x86
        path: d:\a\ezmute-release\standalone-win-x86
    - uses: actions/upload-artifact@v2
      with:
        name: ezmute-win-x64
        path: d:\a\ezmute-release\win-x64
    - uses: actions/upload-artifact@v2
      with:
        name: ezmute-win-x86
        path: d:\a\ezmute-release\win-x86
    - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.SOURCE_BRANCH }}
        release_name: Release ${{ steps.get_version.outputs.SOURCE_BRANCH }}
        draft: true
        prerelease: true
